name: Daily Stock Scan

# Triggers the workflow daily at 6:30 AM UTC
# and allows manual runs from the GitHub UI
on:
  schedule:
    - cron: '30 6 * * *'  # Every day at 6:30 AM UTC
  workflow_dispatch:      # Enables manual trigger

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Stock Scanner Script
        env:
          EMAIL: ${{ secrets.EMAIL }}           # Your email stored as GitHub secret
          PASSWORD: ${{ secrets.PASSWORD }}     # Your app password stored as GitHub secret
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}  # News API key stored as secret
        run: python main.py                     # Change 'main.py' if your script filename is different
